### ISSUE TITLE
build issue: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE\

### ISSUE THREAD

**Issue by maxlklaxl** [srgblnch/python-pylon#1]
I'm trying to build on ubuntu 14.05 (also tested on 12.05), any idea what could cause this issue

thx

```
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    from pylon.version import pyversionstr
  File "/usr/lib/python2.7/dist-packages/pyximport/pyximport.py", line 424, in load_module
    language_level=self.language_level)
  File "/usr/lib/python2.7/dist-packages/pyximport/pyximport.py", line 210, in load_module
    mod = imp.load_dynamic(name, so_path)
ImportError: Building module pylon failed: ['ImportError: /home/strawlab/.pyxbld/lib.linux-x86_64-2.7/pylon/__init__.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_info
 undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE\n']
```

**Comment by srgblnch** [comment]
It looks a link error because of a symbol of cxxabiv1 dynamic library that perhaps is not in the LD_LIBRARY_PATH. But I didn't thought the module has depending on that library.
