### ISSUE TITLE
firstAproach branch does not build

### ISSUE THREAD

**Issue by mabl** [srgblnch/python-pylon#2]
Hi,

thank you very much for this work. Unfortunatly, I cannot build the default firstAproach branch. The master branch works, but import fails. I'll open a second issue.

```
./setup.sh      
Environment for Pylon 2 arch64
/opt/pylon/lib64:/opt/pylon/lib64/pylon/tl/:/opt/pylon/genicam/bin/Linux64_x64:/opt/pylon/pylon/bin
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:1354:91: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__GenApi_3a__3a_EVisibility(enum GenApi::EVisibility value);
                                                                                           ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:1356:94: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__GenApi_3a__3a_EInterfaceType(enum GenApi::EInterfaceType value);
                                                                                              ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c: In function ‘void __pyx_tp_dealloc_5pylon_8__init_____CDeviceInfo(PyObject*)’:
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:27142:39: error: ‘__Pyx_call_destructor’ was not declared in this scope
   __Pyx_call_destructor(p->_DeviceInfo);
                                       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c: In function ‘void __pyx_tp_dealloc_5pylon_8__init_____CBaslerGigEDeviceInfo(PyObject*)’:
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:27499:49: error: ‘__Pyx_call_destructor’ was not declared in this scope
   __Pyx_call_destructor(p->_baslerGigEDeviceInfo);
                                                 ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c: At global scope:
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33193:91: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__GenApi_3a__3a_EVisibility(enum GenApi::EVisibility value) {
                                                                                           ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c: In function ‘PyObject* __Pyx_PyInt_From_enum__GenApi_3a__3a_EVisibility(int)’:
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33194:24: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
     const enum GenApi::EVisibility neg_one = (enum GenApi::EVisibility) -1, const_zero = (enum GenApi::EVisibility) 0;
                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33194:60: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
     const enum GenApi::EVisibility neg_one = (enum GenApi::EVisibility) -1, const_zero = (enum GenApi::EVisibility) 0;
                                                            ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33195:39: error: ‘const_zero’ was not declared in this scope
     const int is_unsigned = neg_one > const_zero;
                                       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33197:33: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
         if (sizeof(enum GenApi::EVisibility) < sizeof(long)) {
                                 ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33199:40: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
         } else if (sizeof(enum GenApi::EVisibility) <= sizeof(unsigned long)) {
                                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33201:40: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
         } else if (sizeof(enum GenApi::EVisibility) <= sizeof(unsigned PY_LONG_LONG)) {
                                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33205:33: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
         if (sizeof(enum GenApi::EVisibility) <= sizeof(long)) {
                                 ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33207:40: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
         } else if (sizeof(enum GenApi::EVisibility) <= sizeof(PY_LONG_LONG)) {
                                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33214:65: error: using typedef-name ‘GenApi::EVisibility’ after ‘enum’
         return _PyLong_FromByteArray(bytes, sizeof(enum GenApi::EVisibility),
                                                                 ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:78:7: note: ‘GenApi::EVisibility’ has a previous declaration here
     } EVisibility;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33215:47: error: in argument to unary !
                                      little, !is_unsigned);
                                               ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c: At global scope:
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33219:94: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__GenApi_3a__3a_EInterfaceType(enum GenApi::EInterfaceType value) {
                                                                                              ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c: In function ‘PyObject* __Pyx_PyInt_From_enum__GenApi_3a__3a_EInterfaceType(int)’:
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33220:24: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
     const enum GenApi::EInterfaceType neg_one = (enum GenApi::EInterfaceType) -1, const_zero = (enum GenApi::EInterfaceType) 0;
                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33220:63: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
     const enum GenApi::EInterfaceType neg_one = (enum GenApi::EInterfaceType) -1, const_zero = (enum GenApi::EInterfaceType) 0;
                                                               ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33221:39: error: ‘const_zero’ was not declared in this scope
     const int is_unsigned = neg_one > const_zero;
                                       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33223:33: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
         if (sizeof(enum GenApi::EInterfaceType) < sizeof(long)) {
                                 ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33225:40: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
         } else if (sizeof(enum GenApi::EInterfaceType) <= sizeof(unsigned long)) {
                                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33227:40: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
         } else if (sizeof(enum GenApi::EInterfaceType) <= sizeof(unsigned PY_LONG_LONG)) {
                                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33231:33: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
         if (sizeof(enum GenApi::EInterfaceType) <= sizeof(long)) {
                                 ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33233:40: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
         } else if (sizeof(enum GenApi::EInterfaceType) <= sizeof(PY_LONG_LONG)) {
                                        ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33240:65: error: using typedef-name ‘GenApi::EInterfaceType’ after ‘enum’
         return _PyLong_FromByteArray(bytes, sizeof(enum GenApi::EInterfaceType),
                                                                 ^
In file included from /home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:249:0:
/opt/pylon/genicam/library/CPP/include/GenApi/Types.h:206:7: note: ‘GenApi::EInterfaceType’ has a previous declaration here
     } EInterfaceType;
       ^
/home/mabl/.pyxbld/temp.linux-x86_64-2.7/pyrex/pylon/__init__.c:33241:47: error: in argument to unary !
                                      little, !is_unsigned);
                                               ^
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    from pylon.version import pyversionstr
  File "/usr/lib/python2.7/site-packages/pyximport/pyximport.py", line 428, in load_module
    language_level=self.language_level)
  File "/usr/lib/python2.7/site-packages/pyximport/pyximport.py", line 227, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/usr/lib/python2.7/site-packages/pyximport/pyximport.py", line 209, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/usr/lib/python2.7/site-packages/pyximport/pyximport.py", line 186, in build_module
    reload_support=pyxargs.reload_support)
  File "/usr/lib/python2.7/site-packages/pyximport/pyxbuild.py", line 100, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "/usr/lib64/python2.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python2.7/distutils/unixccompiler.py", line 122, in _compile
    raise CompileError, msg
ImportError: Building module pylon failed: ["CompileError: command 'g++' failed with exit status 1\n"]
```

**Comment by srgblnch** [comment]
The first approach branch was a test that didn't work as expected. The idea is to remove this branch in the future, but I like to maintain there to be sure the code there is not reusable.

**Comment by mabl** [comment]
Yep, got it know. I was just mislead because it is the project's default branch instead of the usual master.

**Comment by srgblnch** [comment]
fixed the "default branch" issue
